[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "its-accessor"
version = "0.1.0"
dependencies = [
    "python-redmine"
]

[tool.setuptools]
packages = ["its_accessor"]